fix: :bug: Check GitHub Secrets variables

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,6 +13,16 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v3
 
+      
+      - name: 🔍 Verificar Variables en GitHub Actions
+        run: |
+          echo " REGISTRATION_DB_URL is set" && test -n "${{ secrets.REGISTRATION_DB_URL }}" && echo " OK" || echo " MISSING"
+          echo " LOGIN_DB_URL is set" && test -n "${{ secrets.LOGIN_DB_URL }}" && echo " OK" || echo " MISSING"
+          echo " LOGOUT_DB_URL is set" && test -n "${{ secrets.LOGOUT_DB_URL }}" && echo " OK" || echo " MISSING"
+          echo " JWT_SECRET_KEY is set" && test -n "${{ secrets.JWT_SECRET_KEY }}" && echo " OK" || echo " MISSING"
+          echo " JWT_ALGORITHM is set" && test -n "${{ secrets.JWT_ALGORITHM }}" && echo " OK" || echo " MISSING"
+          echo " JWT_EXPIRATION_MINUTES is set" && test -n "${{ secrets.JWT_EXPIRATION_MINUTES }}" && echo " OK" || echo " MISSING"
+
       - name: Configurar SSH y desplegar en EC2
         env:
           REGISTRATION_DB_URL: ${{ secrets.REGISTRATION_DB_URL }}
